package com.cleverm.smartpen.statistic.dao;

import android.database.sqlite.SQLiteDatabase;


import com.cleverm.smartpen.statistic.model.Stats;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig statsDaoConfig;

    private final StatsDao statsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        statsDaoConfig = daoConfigMap.get(StatsDao.class).clone();
        statsDaoConfig.initIdentityScope(type);

        statsDao = new StatsDao(statsDaoConfig, this);

        registerDao(Stats.class, statsDao);
    }
    
    public void clear() {
        statsDaoConfig.getIdentityScope().clear();
    }

    public StatsDao getStatsDao() {
        return statsDao;
    }

}
